export type AccountReceivableMovementType = 'CARGO' | 'ABONO';

/**
 * "Cuentas por Cobrar" — a client-linked Kardex/ledger of money the client
 * owes: every row is a `CARGO` (adds to the balance) or `ABONO` (reduces
 * it) movement, `amount` always a positive magnitude (see migration
 * `CreateFinancialKardexColumns`). The client's current balance adds into
 * the daily Cuadre Agentes result (`Cash + Banks + AccountsReceivable −
 * Assets`, see `GetCuadreAgentesSummaryUseCase` in the banks module).
 * Structurally a clone of `Asset` — see that entity's own doc comment for
 * the one deliberate behavioral delta: `register_account_receivable_movement`
 * rejects an `ABONO` larger than the client's current balance
 * (`ABONO_EXCEEDS_BALANCE`) — this table's `amount` has never allowed a
 * negative representation (`CHK_accounts_receivable_amount_positive` never
 * lapsed, unlike `assets`' own history), so this preserves that existing
 * rule exactly rather than introducing a new one.
 */
export interface AccountReceivableProps {
  id: string;
  clientId: string;
  clientName: string;
  date: string;
  amount: number;
  /** Always a positive magnitude — the sign is `movementType`, never encoded in `amount` itself. */
  movementType: AccountReceivableMovementType;
  sequence: number;
  description: string | null;
  /** Polymorphic origin tag — `null` for a movement registered directly through Cuentas por Cobrar. `'BANK_DEPOSIT'` + a `bank_deposit_operations.id` when this CARGO was generated by Transaccionar's "Enviar a cuentas por cobrar". */
  referenceType: string | null;
  referenceId: string | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  createdByUsername: string;
  updatedBy: string | null;
  updatedByUsername: string | null;
}

export class AccountReceivable {
  private constructor(private readonly props: AccountReceivableProps) {}

  static create(props: AccountReceivableProps): AccountReceivable {
    return new AccountReceivable(props);
  }

  get id(): string {
    return this.props.id;
  }

  get clientId(): string {
    return this.props.clientId;
  }

  get clientName(): string {
    return this.props.clientName;
  }

  get date(): string {
    return this.props.date;
  }

  get amount(): number {
    return this.props.amount;
  }

  get movementType(): AccountReceivableMovementType {
    return this.props.movementType;
  }

  get sequence(): number {
    return this.props.sequence;
  }

  get description(): string | null {
    return this.props.description;
  }

  get referenceType(): string | null {
    return this.props.referenceType;
  }

  get referenceId(): string | null {
    return this.props.referenceId;
  }

  get isActive(): boolean {
    return this.props.isActive;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get createdBy(): string {
    return this.props.createdBy;
  }

  get createdByUsername(): string {
    return this.props.createdByUsername;
  }

  get updatedBy(): string | null {
    return this.props.updatedBy;
  }

  get updatedByUsername(): string | null {
    return this.props.updatedByUsername;
  }
}
